### ISSUE TITLE
genEncounter.sqf

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#1]
### Overview
Generates a random encounter based on parameters provided. Should aggregate enemies, objects, containers, weapons, support calls, ambient sounds, post processing affects, and environmental hazards to create an unique and interesting experience.

```sqf
_someEncounter = ["mkr_1", [1, 2, 3], 1, 2, 2] call genEncounter;

// _factions: 0=CIVILIAN, 1=EAST, 2=GUER
// _difficulty: ...
```

### Params
* `_marker`
* `_factions` - all possible factions for encounter; default = all
* `_zone` - zone type to determine encounter objectives
* `_size` - determines number of groups
* `_difficulty` - will eventually influence ai skills and weapon upgrades

### Tasks
* [x] research global variables: safety, multiplayer implications etc. Determine if roles could be included in config.sqf, i.e `roleName = #include "\roles\faction\roleName.sqf"`

> Per this [kzk article](http://killzonekid.com/arma-scripting-tutorials-variables-part-2/), I'm considering including all subroutines related to the population module into several inline functions within one larger script.

* [ ] create function `getRole // lists equipment and behaviors for a role`
* [ ] create function `genGroup // generates a random group comprised of multiple unit roles`
* [ ] create function `genEncounter // generates a random encounter comprised of multiple collections of compatible groups, containers, and objects`
* [x] create a single asset pool file for each of `[objectives, roles, ammo, uniforms, vehicles, weapons, items, zones, encounters]`
* [ ] create function `genObjects // generates a random group of related objects` -- #9 
* [ ] ensure that `genObjects` function allows for unique objects to be specified; probably through another list if that's not too ugly (example: gas station buildings spawning adjacent would look dumb
* [ ] create function `genContainers // generates a random number of containers near an encounter and populates them with gear based on encounter`.

> I think the point kzk is making is that with well-structured code, you shouldn't need 200+ lines of code, and the headers on each file are growing tremendously at this point.

> Furthermore, after seeing how (very) poorly Arma navigated directory trees (I spent 2+ hours in `#include "module\population\someFileBackOneDirectory.sqf"`-hell last night before I was aware of this), there is definitely something to be said for condensing the number of files to manage through the Arma runtime compiler.

* [ ] modify the T8_spawnGroup function to `call genEncounters` for a zone, instead creating individual groups with init scripts

### Issues
T8 units imposes some limitations on randomly generating unit loadouts on a group by group basis:

* currently, T8 units spawns groups of units but requires the use of an init script in order to customize unit loadouts
* obviously, the init script causes each unit to individually roll for a loadout, and groups are *completely* random instead of being a collection of similarly armed units form one recognizable unit role.
