### ISSUE TITLE
Support call-ins

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#2]
## Tasks
* [ ] create function `genSupportCall // generates a random support call`
* [ ] create function `addSupportCall // adds a support call to a player`
* [ ] create function `remSupportCall // removes a support call from a player`
* [ ] create function `viewSupportMenu // displays the support call menu`
* [ ] create function `useSupportCall // eventHandler based on support call type `
* [ ] create function `addSupportToken // adds a support token to a player`
* [ ] create function `remSupportToken // removes a support token from a player`

## Overview
1. players receive a random number of support tokens for completing tasks
1. support call-ins may be used at the cost of _x support tokens, depending on the cost of the call-in
1. players without tokens may not use support call-ins, but the call-ins should remain visible to maintain consistency

## Example 1
* players should not be able to trade support tokens
* players start with 2 or 3 usable support call-ins (random-basic call-ins most likely, not random-all)
* support tokens can be used to purchase access to new support call-ins
* purchase of additional support call-ins involves players choosing a particular **support tier**, and randomly generating a call in from that tier
* owned support call-ins should **not** be included in future rolls

## Example 2
* players receive tokens and purchase from defined *support tiers* as above
* the purchase of new call-ins involves the player obtaining a random **single-use** support call-in from the chosen tier (duplicate call-ins are permitted)
* on player start, 2-3 random supports could be owned, randomly chosen from multiple lower tiers
