### ISSUE TITLE
addGlow

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#30]
### Tasks
* [ ] create base rvmat
* [ ] create rvmat for each type of color
* [ ] create `addGlow` function

Apply `setObjectMaterial` to object, with color matching a specified parameter. Glow affects will be used to provide subtle hints to players on object purpose or functionality, i.e:

* objectives
* items
* resources
* base management
