### ISSUE TITLE
Dynamic object coloring

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#31]
### Tasks
* [ ] research performance implications of spawning a large number of civilian vehicles & clothing etc. using procedural textures + rvmat overlays
* [ ] create separate texture indexes for uniforms & clothing tops and bottoms (i.e. pants color can be dynamically generated separate from shirt color)
* [ ] create separate texture indexes for vehicle body textures (i.e. color of civilian vehicles can be set separate from bumper, wheels or other elements
* [ ] test performance using 100+ vehicle + civilian textures in memory -- loading time, screen lag?
* [ ] create rvmat texture for semi-gloss clothing
* [ ] create rvmat texture for flat clothing
* [ ] create rvmat texture for new metal
* [ ] create rvmat texture for rusty metal
* [ ] create rvmat texture for dark metal
* [ ] create rvmat texture for new plastic
* [ ] create rvmat texture for sun-bleached plastic
* [ ] create rvmat texture for old plastic
* [ ] create rvmat texture for semi-gloss powder-coated vehicles

> shader types used in place of textures during shader stages? https://community.bistudio.com/wiki/Super_shader

Apply stylized coloring to objects using [procedural textures](https://community.bistudio.com/wiki/Procedural_Textures) and general rvmats for a range of materials, i.e:

* spawn civilian vehicles in an unlimited number of colors
* apply a consistent, modern texture scheme to all units
* utilize older / community created content, updated with a modern set of rvmat material textures to ensure all models are modern and appealing

**Comment by devynspencer** [comment]
If I understand the BIS super shader correctly, their use is almost identical to the generation of procedural textures (colors), i.e:
```
texture="#(argb,8,8,3)color(0.5,0.5,1,1)"; 
```

The difference between the two is where they are called from, i.e. including the above in an .rmvat file instead of a script.

https://community.bistudio.com/wiki/Super_shader
