### ISSUE TITLE
Integrate other BIS content

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#32]
### Tasks
* [ ] check licenses
* [ ] check for community content that has already been ported

Update models, configs, and textures for each of the following:

* [ ] Take On Helicopters content
* [ ] Arma 2 OA content
* [ ] Arma 2 content
* [ ] Dayz Standalone content
* [ ] community content -- [CUPS](http://www.armaholic.com/page.php?id=27489)
