### ISSUE TITLE
Constructable assets

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#5]
## Tasks
* [ ]  implement player-constructable assets, i.e. small radio towers, radio jamming stations, supply stashes, outposts, camps, observation towers, basic shelters, traps, barricades
* [ ] create color / icon-driven tile menu for crafting structures and placing them in the world
* [ ] create persistence logic for storing structures in memory

A big one, with many requirements.
