### ISSUE TITLE
Rare encounters

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#6]
Create separate category of rare encounters with significantly higher difficulty & rewards, i.e:

* Airdrops & supply caches
* Crashed enemy helo

### Tasks
* [ ] random airdrops as a zone encounter
* [ ] airdrops have the potential to spawn (difficult) groups of nearby enemies looking to retrieve the contents
* [ ] supply caches spawn an abnormal amount of loot and always contain patrols of difficult enemy groups
* [ ] depending on enemies included in encounter, supply caches may be booby-trapped (nearby area) or under overwatch
