### ISSUE TITLE
Develop module structure

### ISSUE THREAD

**Issue by devynspencer** [devynspencer/arma-valkyrie#7]
### Tasks
* [x] identify dependencies or other oddities, i.e. `#include "file.sqf` can't reference previous directories
* [ ] identify core (reusable) components of modules
* [ ] design a folder structure that provides the best environment for the above
